apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: paulooo/customized-hw:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: backend-tester
spec:
  containers:
    - name: backend-tester
      image: curlimages/curl:latest
      command: ["sh", "-c", "sleep 3600"]
