apiVersion: v1
kind: PersistentVolume
metadata:
  name: exercise-5-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ./data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exercise-5-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
